# nLobbyBlocks Configuration

blocks-on-join: true
prevent-drop: true
prevent-move: true
prevent-off-hand-swap: true

block-type: MOSS_BLOCK
block-name: "&dʙʟᴏᴄᴄʜɪ ᴍᴀɢɪᴄɪ &7(ᴄʟɪᴄᴋ ᴅᴇꜱᴛʀᴏ)"
block-count: 64

hotbar-slot: 0

join-give-delay:
  enable: true
  delay: 20 # Ticks (20 Ticks = 1 Second)

break-after: 10 # Seconds

environment:
  prevent-block-interaction: false

sounds:
  place:
    enabled: false
    sound: BLOCK_NOTE_BLOCK_PLING
    volume: 1.0
    pitch: 1.2
  break:
    enabled: false
    sound: BLOCK_GRASS_BREAK
    volume: 1.0
    pitch: 1.0


regions:
  # example:
  #   world: world
  #   min:
  #     x: -100
  #     y: 60
  #     z: -100
  #   max:
  #     x: 100
  #     y: 100
  #     z: 100
